### PR TITLE
fix: Rename Namespace MR to VaultNamespace

### LINKED ISSUE #12: Unable to create namespace
### What happened?

Unable to create vault namespace getting "Resource not found error"

Epic #

### How can we reproduce it?

apiVersion: vault.vault.upbound.io/v1alpha1
kind: Namespace
metadata:
  name: vault-namespace
spec:
  forProvider:
    namespace: "<Namespace>"
    path: "<PATH>"

### PR DESCRIPTION
**Pull request by jaylevin**
### Description of your changes

- Renames the Provider's `Namespace` resource to `VaultNamespace` in order to resolve naming conflict with the K8s native `Namespace` resource.

Fixes #12  (and the duplicate #31)

I have:

- [X] Read and followed Crossplane's [contribution process].
- [X] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Tested in a kubernetes cluster on Crossplane v1.15.1 and kubernetes v1.26

[contribution process]: https://git.io/fj2m9

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -8,7 +8,7 @@ export TERRAFORM_VERSION := 1.5.5
 
 export TERRAFORM_PROVIDER_SOURCE ?= hashicorp/vault
 export TERRAFORM_PROVIDER_REPO ?= https://github.com/hashicorp/terraform-provider-vault
-export TERRAFORM_PROVIDER_VERSION ?= 3.25.0
+export TERRAFORM_PROVIDER_VERSION ?= 4.2.0
```
Comment (abhigarg28) [inline Makefile:11]: @jaylevin Are there any breaking changes we should be aware of?

File: apis/identity/v1alpha1/zz_oidcclient_types.go [hunk 2]
```diff
@@ -67,6 +67,7 @@ type OidcClientObservation struct {
 	// A list of assignment resources associated with the client.
 	Assignments []*string `json:"assignments,omitempty" tf:"assignments,omitempty"`
 
+	// The Client ID returned by Vault.
 	// The Client ID from Vault.
```
Comment (abhigarg28) [inline apis/identity/v1alpha1/zz_oidcclient_types.go:71]: Nitpick, I would clean up the duplicate comment here.

Comment (jaylevin) [reply apis/identity/v1alpha1/zz_oidcclient_types.go:71]: This is auto-generated code we don't have much of a choice.

Comment (jaylevin) [reply apis/identity/v1alpha1/zz_oidcclient_types.go:71]: There's an open issue for this bug upjet: https://github.com/crossplane/upjet/issues/371

File: Makefile (hunk 1 above)
Comment (jaylevin) [reply Makefile:11]: There is one "blocking change" that will prevent the deployment of new read policies that aren't set at the path level. The Vault Provider maintainers put together an upgrade guide for v4.0.0 and it's basically just updating the policy permissions to be set at the path level for mount metadata.

From the Vault Provider TF repository release notes from v3.25.0 -> 4.0.0:

> Important: This major version release includes performance improvements for deployments that manage many Vault secret or auth engine mounts. This release requires read policies to be set at the path level for mount metadata. For example, instead of permissions at sys/auth you must set permissions at the sys/auth/:path level. Please refer to the details in the [Terraform Vault Provider 4.0.0 Upgrade Guide](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/guides/version_4_upgrade).

From the version 4.0.0 upgrade guide:

> The changes in this case are blocking but not destructive. That is, deployments will fail until the required Vault policy adjustments have been made.

Comment (abhigarg28) [reply Makefile:11]: sounds good, release notes should take care of explaining that. @haarchri right?

**Review by abhigarg28 — APPROVED** [review]

File: .github/workflows/ci.yml [hunk 3]
```diff
@@ -77,6 +77,8 @@ jobs:
         uses: golangci/golangci-lint-action@v3
         with:
           version: ${{ env.GOLANGCI_VERSION }}
+          skip-pkg-cache: true
+          skip-build-cache: true
```
Comment (jaylevin) [inline .github/workflows/ci.yml:81]: I had to add these to get past some CI errors.

File: config/vault_namespace/config.go [hunk 4]
```diff
@@ -0,0 +1,13 @@
+package vault_namespace
+
+import "github.com/upbound/upjet/pkg/config"
+
+// ConfigureNamespace configures the namespace resource.
+func Configure(p *config.Provider) {
+	p.AddResourceConfigurator("vault_namespace", func(r *config.Resource) {
+		r.Kind = "VaultNamespace"
+		r.ShortGroup = "vault"
+		r.UseAsync = true
```
Comment (sergenyalcin) [inline config/vault_namespace/config.go:10]: nit: The value of the configuration is `true` in upjet by default. If you do not specify explicitly here, still it should be `true`.

File: Makefile (hunk 1 above)
Comment (sergenyalcin) [inline Makefile:11]: It looks like there's already been a discussion about this part. I want to mention a few things. During such major version bumps, it would be nice if the resources with changes in the API were tested and there was a note in the PR description that these were tested.

Also, as already mentioned, it would be beneficial for users to clearly state the relevant breaking changes in the Release Notes.

As a final point of discussion, since this upgrade causes breaking change, does it make sense to do a major version bump after the relevant PR merge? So, releasing `1.0.0`.

File: config/vault_namespace/config.go
[the remark this answers is not in the document]
Comment (jaylevin) [reply config/vault_namespace/config.go:1]: Done 👍

File: config/vault_namespace/config.go (hunk 4 above)
Comment (jaylevin) [reply config/vault_namespace/config.go]: Done 👍

File: config/vault_namespace/config.go [hunk 5]
```diff
@@ -0,0 +1,13 @@
...
+		r.ExternalName = config.IdentifierFromProvider
```
[the remark this answers is not in the document]
Comment (jaylevin) [reply config/vault_namespace/config.go]: Done 👍

File: Makefile (hunk 1 above)
Comment (jaylevin) [reply Makefile:11]: > It looks like there's already been a discussion about this part. I want to mention a few things. During such major version bumps, it would be nice if the resources with changes in the API were tested and there was a note in the PR description that these were tested.
> 
> Also, as already mentioned, it would be beneficial for users to clearly state the relevant breaking changes in the Release Notes.
> 
> As a final point of discussion, since this upgrade causes breaking change, does it make sense to do a major version bump after the relevant PR merge? So, releasing `1.0.0`.

Thanks for the review @sergenyalcin , and it makes sense to me to do a major version bump 👍 I will continue with testing the resources with changes to the API and update the PR description ASAP.

Comment (jaylevin) [reply Makefile]: @sergenyalcin Update: I noticed a couple issues with resources going out of sync while testing with the new terraform (v4.5.0). In the interest of time and priority, I reverted the changes for the terraform provider version upgrade and instead would like this PR to focus on solely addressing #12.

File: .golangci.yml [hunk 6]
```diff
@@ -1,12 +1,16 @@
-run:
```
Comment (jaylevin) [inline .golangci.yml:1]: I synced this file with the contents of provider-aws.

**Review by sergenyalcin — APPROVED** [review]
Thanks @jaylevin LGTM!

**Comment by jaylevin** [comment]
> Thanks @jaylevin LGTM!

Thanks @sergenyalcin! It looks like I don't have write permission to merge this pull request. Is it possible for you to merge this the next time you can get a chance?
